### PR TITLE
Please remove coupling with brolog

### PR DESCRIPTION
**Pull request by carlosdelfino**

### CODE REVIEW

**Comment by zixia** [comment]
Hi, thanks for the contribution!

However, could you please share the motivation of why you are willing to do this? I'd like to keep it unless it is really hurt the user development & production experience.

The reasons I'd like to keep using Brolog is because:
1. I need to show the debug information for debugging(when we needed).
1. Brolog code is very tiny and it can be ignored(I'm sure about it coz it is written by me).
1. It can run both inside Browser and under Node without any problem(compatible with Angular too).

**Comment by carlosdelfino** [comment]
Acoplar plugins a uma ferramenta de depuração forançando que o ambiente final também venha a ter que usa-lo torna o ambiente de desenvolvimento uma mistura de ferramentas de depuração.

Cada desenvolvedor ver em um ambiente de depuração a sua melhor escolha, e no final acabamos tendo uma variade de plugins de depuração sendo usados cada um para um plugin.

entendo que este plugin ainda esteja em desenvolvimento, mas nos testes que fiz demonstrou a maturidade necessária a demanda que tive, mas me incomodou ter mais uma ferramenta de depuração além da que já uso.

Eu fiz a remoção já que não impacta na funcionalidade proposta, e sugeri o merge.

Em meu ambiente quando preciso depurar algo com inserção de códigos de testes, uso um branch a parte que não é o principal para distribuição.

**Comment by carlosdelfino** [comment]
Coupling plugins to a debugging tool leading to the final environment also having to use it makes the development environment a mixture of debugging tools.

Each developer sees in a debugging environment their best choice, and in the end we end up having a variety of debugging plugins being used each for a plugin.

I understand that this plugin is still in development, but in the tests I did it showed the necessary maturity the demand I had, but it bothered me to have another debugging tool besides the one I already use.

I did the removal since it did not impact on the proposed functionality, and I suggested the merge.

In my environment when I need to debug something with test code insertion, I use a branch that is not the primary part for distribution.

**Comment by zixia** [comment]
After thinking about your opinions again it seems that I will agree with you: remove the `Brolog` module from the production code because make the module cleaner is better for the production environment.

So let's remove it. 

However, could you please to make sure the CI keeps green before we could merge your PR? It needs to make the tslint happy, the error is the following:

```
tslint v5.9.1
typeof-compare is deprecated. Starting from TypeScript 2.2 the compiler includes this check which makes this rule redundant.
ERROR: /home/travis/build/zixia/rx-queue/src/delay-queue.ts[20, 1]: trailing whitespace
ERROR: /home/travis/build/zixia/rx-queue/src/throttle-queue.ts[17, 1]: trailing whitespace
```

Thanks for discussing this with me and the contribution!

**Comment by zixia** [comment]
Merged. Thank you for the contribution!

**Comment by carlosdelfino** [comment]
thanks.

**Pull request merged**
